# Generated by Django 4.2.2 on 2024-05-09 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_alter_profile_appointment1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='appointment1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='appointment2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='appointment3',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='appointment4',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='appointment5',
        ),
    ]
