# Generated by Django 4.2.2 on 2024-05-10 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Advisor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الجلسة'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_reason',
            field=models.CharField(max_length=255, null=True, verbose_name='سبب الجلسة'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_time',
            field=models.TimeField(null=True, verbose_name='وقت الجلسة'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='session_type',
            field=models.CharField(choices=[('video', 'فيديو'), ('audio', 'صوت'), ('text', 'رسائل')], max_length=50, null=True, verbose_name='نوع الجلسة'),
        ),
        migrations.CreateModel(
            name='AvailableTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('is_booked', models.BooleanField(default=False, verbose_name='Is Booked')),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_times', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
